const base = {
  colors: {
    primary_1: '#38cea1',
    primary_2: '#418677',
    primary_3: '#426659',

    secondary_1: '#75a6d4',
    secondary_2: '#b4c4e6',
    secondary_3: '#72b5f3',
    secondary_4: '#7390AA',
    
    tertiary_1: '#646c9e',
    tertiary_2: '#5d6077',
    tertiary_3: '#38393f',

    bg: '#0e1016',
    brightYellow: '#fffac2',
    hotRed: '#d0679d',
    pink: '#f087bd',
    gray: '#a6accd',

    offWhite: '#cdd8e2',
    selection: '#717cb425',

    white: '#ffffff',
    black: '#000000',
    transparent: '#00000000',
  },
  styles: {
    fontStyle: '',
  },
}

const noitalics = { ...base, styles: { ...base.styles, fontStyle: '' } }

const storm = {
  ...base,
  colors: {
    ...base.colors,
    tertiary_1: '#868cad',
    tertiary_2: '#607487',
    tertiary_3: '#404350',
    bg: '#252b37',
    selection: '#818cc425',
    black: '#101010',
  },
}

const stormNoitalics = {
  ...base,
  colors: { ...storm.colors },
  styles: { ...base.styles, fontStyle: '' },
}

function schema({ colors, styles }) {
  return `{
    "name": "poimandres dark theme",
    "type": "dark",
    "colors": {
      "activityBar.background": "${colors.bg}",
      "activityBar.foreground": "${colors.gray}",
      "activityBarBadge.background": "${colors.tertiary_3}",
      "activityBarBadge.foreground": "${colors.offWhite}",
      "badge.background": "${colors.tertiary_3}",
      "badge.foreground": "${colors.offWhite}",
      "button.background": "${colors.tertiary_3}",
      "diffEditor.insertedTextBackground": "${colors.tertiary_2}15",
      "diffEditor.removedTextBackground": "${colors.hotRed}20",
      "dropdown.background": "${colors.bg}",
      "dropdown.border": "${colors.white}10",
      "editor.background": "${colors.bg}",
      "editor.findMatchBackground": "${colors.secondary_2}40",
      "editor.findMatchBorder": "${colors.secondary_2}",
      "editor.findMatchHighlightBackground": "${colors.secondary_2}40",
      "editor.foreground": "${colors.gray}",
      "editor.lineHighlightBackground": "${colors.selection}",
      "editor.lineHighlightBorder": "${colors.transparent}",
      "editor.selectionBackground": "${colors.selection}",
      "editor.selectionHighlightBackground": "${colors.transparent}",
      "editor.selectionHighlightBorder": "${colors.secondary_2}80",
      "editor.wordHighlightBackground": "${colors.secondary_2}20",
      "editor.wordHighlightStrongBackground": "${colors.secondary_2}40",
      "editorBracketMatch.border": "${colors.offWhite}40",
      "editorCursor.foreground": "${colors.gray}",
      "editorGroup.border": "${colors.black}30",
      "editorGroupHeader.tabsBackground": "${colors.bg}",
      "editorHoverWidget.background": "${colors.bg}",
      "editorHoverWidget.border": "${colors.white}10",
      "editorIndentGuide.background": "${colors.tertiary_3}",
      "editorLineNumber.foreground": "${colors.tertiary_1}50",
      "editorLink.activeForeground": "${colors.secondary_2}",
      "editorSuggestWidget.background": "${colors.bg}",
      "editorSuggestWidget.border": "${colors.white}10",
      "editorSuggestWidget.foreground": "${colors.gray}",
      "editorSuggestWidget.highlightForeground": "${colors.primary_1}",
      "editorSuggestWidget.selectedBackground": "${colors.black}50",
      "editorWidget.background": "${colors.bg}",
      "editor.findRangeHighlightBackground": "${colors.secondary_2}40",
      "editor.tertiary_3edStackFrameHighlightBackground": "#7abd7a4d",
      "editor.foldBackground": "#717cb40b",
      "editor.hoverHighlightBackground": "#264f7840",
      "editor.inactiveSelectionBackground": "${colors.selection}",
      "editor.linkedEditingBackground": "${colors.hotRed}4d",
      "editor.rangeHighlightBackground": "${colors.white}0b",
      "editor.snippetFinalTabstopHighlightBorder": "#525252",
      "editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
      "editor.stackFrameHighlightBackground": "#ffff0033",
      "editor.symbolHighlightBackground": "${colors.secondary_1}60",
      "editorBracketMatch.background": "${colors.transparent}",
      "editorCodeLens.foreground": "${colors.gray}",
      "editorError.foreground": "${colors.hotRed}",
      "editorGroup.dropBackground": "${colors.secondary_4}80",
      "editorGroupHeader.noTabsBackground": "${colors.bg}",
      "editorGutter.background": "${colors.bg}",
      "editorGutter.commentRangeForeground": "${colors.gray}",
      "editorGutter.foldingControlForeground": "${colors.gray}",
      "editorGutter.addedBackground": "${colors.primary_2}40",
      "editorGutter.deletedBackground": "${colors.hotRed}40",
      "editorGutter.modifiedBackground": "${colors.secondary_2}20",
      "editorHint.foreground": "${colors.secondary_4}b3",
      "editorHoverWidget.foreground": "${colors.gray}",
      "editorHoverWidget.statusBarBackground": "#202430",
      "editorIndentGuide.activeBackground": "#e3e4e229",
      "editorInfo.foreground": "${colors.secondary_2}",
      "editorInlineHint.background": "${colors.gray}",
      "editorInlineHint.foreground": "${colors.bg}",
      "editorLightBulb.foreground": "${colors.brightYellow}",
      "editorLightBulbAutoFix.foreground": "${colors.secondary_2}",
      "editorLineNumber.activeForeground": "${colors.gray}",
      "editorMarkerNavigation.background": "#2d2d30",
      "editorMarkerNavigationError.background": "${colors.hotRed}",
      "editorMarkerNavigationInfo.background": "${colors.secondary_2}",
      "editorMarkerNavigationWarning.background": "${colors.brightYellow}",
      "editorOverviewRuler.addedForeground": "${colors.primary_2}99",
      "editorOverviewRuler.border": "${colors.transparent}",
      "editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
      "editorOverviewRuler.commonContentForeground": "${colors.gray}66",
      "editorOverviewRuler.currentContentForeground": "${colors.primary_2}80",
      "editorOverviewRuler.deletedForeground": "${colors.hotRed}99",
      "editorOverviewRuler.errorForeground": "${colors.hotRed}b3",
      "editorOverviewRuler.findMatchForeground": "${colors.offWhite}20",
      "editorOverviewRuler.incomingContentForeground": "${colors.secondary_1}80",
      "editorOverviewRuler.infoForeground": "${colors.secondary_2}",
      "editorOverviewRuler.modifiedForeground": "${colors.secondary_1}99",
      "editorOverviewRuler.rangeHighlightForeground": "${colors.secondary_1}99",
      "editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
      "editorOverviewRuler.warningForeground": "${colors.brightYellow}",
      "editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
      "editorOverviewRuler.wordHighlightStrongForeground": "${colors.secondary_1}cc",
      "editorPane.background": "${colors.bg}",
      "editorRuler.foreground": "${colors.offWhite}10",
      "editorUnnecessaryCode.opacity": "${colors.black}aa",
      "editorWarning.foreground": "${colors.brightYellow}",
      "editorWhitespace.foreground": "${colors.tertiary_3}",
      "editorWidget.border": "${colors.gray}",
      "editorWidget.foreground": "${colors.gray}",
      "extensionButton.prominentBackground": "${colors.tertiary_3}90",
      "extensionButton.prominentHoverBackground": "${colors.tertiary_3}",
      "tertiary_3Border": "${colors.transparent}",
      "input.background": "${colors.white}05",
      "input.border": "${colors.white}10",
      "input.foreground": "${colors.offWhite}",
      "input.placeholderForeground": "${colors.gray}60",
      "inputValidation.errorBorder": "${colors.hotRed}",
      "inputValidation.errorForeground": "${colors.hotRed}",
      "inputValidation.infoBorder": "${colors.secondary_1}",
      "inputValidation.warningBorder": "${colors.brightYellow}",
      "notifications.background": "${colors.bg}",
      "notifications.foreground": "${colors.offWhite}",
      "panel.border": "${colors.black}30",
      "panelTitle.activeForeground": "${colors.gray}",
      "peekView.border": "${colors.black}30",
      "peekViewEditor.background": "${colors.gray}05",
      "peekViewEditorGutter.background": "${colors.gray}05",
      "peekViewResult.background": "${colors.gray}05",
      "peekViewTitle.background": "${colors.gray}05",
      "peekViewTitleDescription.foreground": "${colors.gray}60",
      "scrollbar.shadow": "${colors.transparent}",
      "scrollbarSlider.activeBackground": "${colors.gray}25",
      "scrollbarSlider.background": "${colors.black}80",
      "scrollbarSlider.hoverBackground": "${colors.gray}25",
      "selection.background": "${colors.gray}",
      "sideBar.background": "${colors.bg}",
      "sideBar.foreground": "${colors.tertiary_1}",
      "sideBarSectionHeader.background": "${colors.bg}",
      "sideBarTitle.foreground": "${colors.gray}",
      "statusBar.background": "${colors.bg}",
      "statusBar.foreground": "${colors.gray}",
      "statusBar.noFolderBackground": "${colors.bg}",
      "tab.activeBackground": "${colors.tertiary_3}80",
      "tab.activeForeground": "${colors.offWhite}",
      "tab.border": "${colors.transparent}",
      "tab.inactiveBackground": "${colors.bg}",
      "tab.inactiveForeground": "${colors.tertiary_1}",
      "tab.untertiary_3edActiveForeground": "${colors.gray}",
      "tab.activeModifiedBorder": "${colors.secondary_2}",
      "tab.inactiveModifiedBorder": "${colors.secondary_2}80",
      "tab.lastPinnedBorder": "${colors.transparent}",
      "tab.untertiary_3edActiveBackground": "${colors.bg}",
      "tab.untertiary_3edActiveModifiedBorder": "${colors.secondary_2}40",
      "tab.untertiary_3edInactiveBackground": "${colors.bg}",
      "tab.untertiary_3edInactiveForeground": "${colors.gray}80",
      "tab.untertiary_3edInactiveModifiedBorder": "${colors.secondary_2}40",      
      "terminal.ansiBlack": "${colors.bg}",
      "terminal.ansiBlue": "${colors.secondary_1}",
      "terminal.ansiBrightBlack": "${colors.gray}",
      "terminal.ansiBrightBlue": "${colors.secondary_2}",
      "terminal.ansiBrightCyan": "${colors.secondary_2}",
      "terminal.ansiBrightGreen": "${colors.primary_1}",
      "terminal.ansiBrightMagenta": "${colors.pink}",
      "terminal.ansiBrightRed": "${colors.hotRed}",
      "terminal.ansiBrightWhite": "${colors.white}",
      "terminal.ansiBrightYellow": "${colors.brightYellow}",
      "terminal.ansiCyan": "${colors.secondary_1}",
      "terminal.ansiGreen": "${colors.primary_1}",
      "terminal.ansiMagenta": "${colors.pink}",
      "terminal.ansiRed": "${colors.hotRed}",
      "terminal.ansiWhite": "${colors.white}",
      "terminal.ansiYellow": "${colors.brightYellow}",
      "textLink.activeForeground": "${colors.secondary_2}",
      "textLink.foreground": "${colors.secondary_2}",
      "titleBar.activeBackground": "${colors.bg}",
      "titleBar.activeForeground": "${colors.gray}",
      "titleBar.inactiveBackground": "${colors.bg}",
      "titleBar.inactiveForeground": "${colors.tertiary_1}",
      "tree.indentGuidesStroke": "${colors.tertiary_3}",
      "widget.shadow": "${colors.black}30",
      "activityBar.activeBorder": "${colors.gray}",
      "activityBar.dropBorder": "${colors.gray}",
      "activityBar.inactiveForeground": "${colors.gray}66",
      "breadcrumb.activeSelectionForeground": "${colors.offWhite}",
      "breadcrumb.background": "${colors.transparent}",
      "breadcrumb.tertiary_3Foreground": "${colors.offWhite}",
      "breadcrumb.foreground": "${colors.tertiary_1}cc",
      "breadcrumbPicker.background": "${colors.bg}",
      "button.foreground": "${colors.white}",
      "button.hoverBackground": "${colors.tertiary_2}50",
      "button.secondaryBackground": "${colors.gray}",
      "button.secondaryForeground": "${colors.white}",
      "button.secondaryHoverBackground": "${colors.gray}",
      "charts.blue": "${colors.secondary_2}",
      "charts.foreground": "${colors.gray}",
      "charts.green": "${colors.primary_1}",
      "charts.lines": "${colors.gray}80",
      "charts.orange": "${colors.secondary_1}",
      "charts.purple": "${colors.pink}",
      "charts.red": "${colors.hotRed}",
      "charts.yellow": "${colors.brightYellow}",
      "checkbox.background": "${colors.bg}",
      "checkbox.border": "${colors.white}10",
      "checkbox.foreground": "${colors.offWhite}",
      "debugConsole.errorForeground": "${colors.hotRed}",
      "debugConsole.infoForeground": "${colors.secondary_2}",
      "debugConsole.sourceForeground": "${colors.gray}",
      "debugConsole.warningForeground": "${colors.brightYellow}",
      "debugConsoleInputIcon.foreground": "${colors.gray}",
      "debugExceptionWidget.background": "${colors.hotRed}",
      "debugExceptionWidget.border": "${colors.hotRed}",
      "debugIcon.breakpointCurrentStackframeForeground": "${colors.brightYellow}",
      "debugIcon.breakpointDisabledForeground": "${colors.secondary_4}",
      "debugIcon.breakpointForeground": "${colors.hotRed}",
      "debugIcon.breakpointStackframeForeground": "${colors.primary_2}",
      "debugIcon.breakpointUnverifiedForeground": "${colors.secondary_4}",
      "debugIcon.continueForeground": "${colors.secondary_2}",
      "debugIcon.disconnectForeground": "${colors.hotRed}",
      "debugIcon.pauseForeground": "${colors.secondary_2}",
      "debugIcon.restartForeground": "${colors.primary_2}",
      "debugIcon.startForeground": "${colors.primary_2}",
      "debugIcon.stepBackForeground": "${colors.secondary_2}",
      "debugIcon.stepIntoForeground": "${colors.secondary_2}",
      "debugIcon.stepOutForeground": "${colors.secondary_2}",
      "debugIcon.stepOverForeground": "${colors.secondary_2}",
      "debugIcon.stopForeground": "${colors.hotRed}",
      "debugTokenExpression.boolean": "${colors.secondary_1}",
      "debugTokenExpression.error": "${colors.hotRed}",
      "debugTokenExpression.name": "${colors.offWhite}",
      "debugTokenExpression.number": "${colors.primary_2}",
      "debugTokenExpression.string": "${colors.secondary_1}",
      "debugTokenExpression.value": "${colors.gray}99",
      "debugToolBar.background": "${colors.tertiary_3}",
      "debugView.exceptionLabelBackground": "${colors.hotRed}",
      "debugView.exceptionLabelForeground": "${colors.offWhite}",
      "debugView.stateLabelBackground": "${colors.tertiary_3}",
      "debugView.stateLabelForeground": "${colors.gray}",
      "debugView.valueChangedHighlight": "${colors.secondary_1}",
      "descriptionForeground": "${colors.gray}b3",
      "diffEditor.diagonalFill": "${colors.gray}33",
      "dropdown.foreground": "${colors.offWhite}",    
      "errorForeground": "${colors.hotRed}",
      "extensionBadge.remoteBackground": "${colors.tertiary_3}",
      "extensionBadge.remoteForeground": "${colors.offWhite}",
      "extensionButton.prominentForeground": "${colors.white}",
      "extensionIcon.starForeground": "${colors.brightYellow}",
      "foreground": "${colors.gray}",
      "gitDecoration.addedResourceForeground": "${colors.primary_2}",
      "gitDecoration.conflictingResourceForeground": "${colors.hotRed}",
      "gitDecoration.deletedResourceForeground": "${colors.hotRed}",
      "gitDecoration.ignoredResourceForeground": "${colors.tertiary_1}70",
      "gitDecoration.modifiedResourceForeground": "${colors.secondary_2}",
      "gitDecoration.renamedResourceForeground": "${colors.primary_1}",
      "gitDecoration.stageDeletedResourceForeground": "${colors.hotRed}",
      "gitDecoration.stageModifiedResourceForeground": "${colors.secondary_2}",
      "gitDecoration.submoduleResourceForeground": "${colors.secondary_1}",
      "gitDecoration.untrackedResourceForeground": "${colors.primary_1}",
      "icon.foreground": "${colors.gray}",
      "imagePreview.border": "${colors.tertiary_3}",
      "inputOption.activeBackground": "${colors.transparent}",
      "inputOption.activeBorder": "${colors.transparent}",
      "inputOption.activeForeground": "${colors.white}",
      "inputValidation.errorBackground": "${colors.bg}",
      "inputValidation.infoBackground": "${colors.tertiary_2}",
      "inputValidation.warningBackground": "${colors.tertiary_2}",
      "list.deemphasizedForeground": "${colors.tertiary_1}",
      "list.dropBackground": "${colors.tertiary_2}",
      "list.filterMatchBackground": "${colors.secondary_1}60",
      "list.tertiary_3Outline": "${colors.transparent}",
      "list.invalidItemForeground": "${colors.brightYellow}",
      "list.warningForeground": "${colors.brightYellow}",
      "listFilterWidget.background": "${colors.tertiary_3}",
      "listFilterWidget.noMatchesOutline": "${colors.hotRed}",
      "listFilterWidget.outline": "${colors.transparent}",
      "list.activeSelectionBackground": "${colors.tertiary_3}80",
      "list.activeSelectionForeground": "${colors.offWhite}",
      "list.errorForeground": "${colors.hotRed}",
      "list.tertiary_3Background": "${colors.tertiary_3}80",
      "list.tertiary_3Foreground": "${colors.gray}",
      "list.highlightForeground": "${colors.primary_2}",
      "list.hoverBackground": "${colors.tertiary_3}80",
      "list.hoverForeground": "${colors.offWhite}",
      "list.inactiveSelectionBackground": "${colors.tertiary_3}80",
      "list.inactiveSelectionForeground": "${colors.offWhite}",
      "menu.background": "${colors.bg}",
      "menu.foreground": "${colors.offWhite}",
      "menu.selectionBackground": "${colors.tertiary_3}",
      "menu.selectionForeground": "${colors.secondary_4}",
      "menu.separatorBackground": "${colors.tertiary_1}",
      "menubar.selectionBackground": "${colors.selection}",
      "menubar.selectionForeground": "${colors.gray}",
      "merge.commonContentBackground": "${colors.gray}29",
      "merge.commonHeaderBackground": "${colors.gray}66",
      "merge.currentContentBackground": "${colors.primary_2}33",
      "merge.currentHeaderBackground": "${colors.primary_2}80",
      "merge.incomingContentBackground": "${colors.secondary_1}33",
      "merge.incomingHeaderBackground": "${colors.secondary_1}80",
      "minimap.errorHighlight": "${colors.hotRed}",
      "minimap.findMatchHighlight": "${colors.secondary_2}",
      "minimap.selectionHighlight": "${colors.offWhite}40",
      "minimap.warningHighlight": "${colors.brightYellow}",
      "minimapGutter.addedBackground": "${colors.primary_2}80",
      "minimapGutter.deletedBackground": "${colors.hotRed}80",
      "minimapGutter.modifiedBackground": "${colors.secondary_2}80",
      "minimapSlider.activeBackground": "${colors.gray}30",
      "minimapSlider.background": "${colors.gray}20",
      "minimapSlider.hoverBackground": "${colors.gray}30",
      "notebook.cellBorderColor": "${colors.bg}",
      "notebook.cellInsertionIndicator": "${colors.transparent}",
      "notebook.cellStatusBarItemHoverBackground": "${colors.white}26",
      "notebook.cellToolbarSeparator": "${colors.tertiary_3}",
      "notebook.tertiary_3edCellBorder": "${colors.transparent}",
      "notebook.tertiary_3edEditorBorder": "${colors.transparent}",
      "notebook.tertiary_3edRowBorder": "${colors.transparent}",
      "notebook.inactivetertiary_3edCellBorder": "${colors.transparent}",
      "notebook.outputContainerBackgroundColor": "${colors.bg}",
      "notebook.rowHoverBackground": "${colors.tertiary_3}00",
      "notebook.selectedCellBackground": "${colors.tertiary_3}",
      "notebook.selectedCellBorder": "${colors.bg}",
      "notebook.symbolHighlightBackground": "${colors.white}0b",
      "notebookScrollbarSlider.activeBackground": "${colors.gray}25",
      "notebookScrollbarSlider.background": "${colors.black}50",
      "notebookScrollbarSlider.hoverBackground": "${colors.gray}25",
      "notebookStatusErrorIcon.foreground": "${colors.hotRed}",
      "notebookStatusRunningIcon.foreground": "${colors.gray}",
      "notebookStatusSuccessIcon.foreground": "${colors.primary_2}",
      "notificationCenterHeader.background": "${colors.tertiary_3}",
      "notificationLink.foreground": "${colors.secondary_2}",
      "notifications.border": "${colors.tertiary_3}",
      "notificationsErrorIcon.foreground": "${colors.hotRed}",
      "notificationsInfoIcon.foreground": "${colors.secondary_2}",
      "notificationsWarningIcon.foreground": "${colors.brightYellow}",
      "panel.background": "${colors.bg}",
      "panel.dropBorder": "${colors.gray}",
      "panelSection.border": "${colors.bg}",
      "panelSection.dropBackground": "${colors.secondary_4}80",
      "panelSectionHeader.background": "${colors.tertiary_3}",
      "panelTitle.activeBorder": "${colors.gray}",
      "panelTitle.inactiveForeground": "${colors.gray}99",
      "peekViewEditor.matchHighlightBackground": "${colors.tertiary_3}",
      "peekViewResult.fileForeground": "${colors.white}",
      "peekViewResult.lineForeground": "${colors.gray}",
      "peekViewResult.matchHighlightBackground": "${colors.tertiary_3}",
      "peekViewResult.selectionBackground": "${colors.selection}",
      "peekViewResult.selectionForeground": "${colors.white}",
      "peekViewTitleLabel.foreground": "${colors.white}",
      "pickerGroup.border": "${colors.gray}",
      "pickerGroup.foreground": "${colors.secondary_1}",
      "problemsErrorIcon.foreground": "${colors.hotRed}",
      "problemsInfoIcon.foreground": "${colors.secondary_2}",
      "problemsWarningIcon.foreground": "${colors.brightYellow}",
      "progressBar.background": "${colors.secondary_1}",
      "quickInput.background": "${colors.bg}",
      "quickInput.foreground": "${colors.gray}",
      "quickInputList.tertiary_3Background": "${colors.gray}10",
      "quickInputTitle.background": "${colors.white}1b",
      "sash.hoverBorder": "${colors.transparent}",
      "scm.providerBorder": "${colors.offWhite}10",
      "searchEditor.findMatchBackground": "${colors.secondary_2}50",
      "searchEditor.textInputBorder": "${colors.white}10",
      "settings.checkboxBackground": "${colors.bg}",
      "settings.checkboxBorder": "${colors.white}10",
      "settings.checkboxForeground": "${colors.offWhite}",
      "settings.dropdownBackground": "${colors.bg}",
      "settings.dropdownBorder": "${colors.white}10",
      "settings.dropdownForeground": "${colors.offWhite}",
      "settings.dropdownListBorder": "${colors.offWhite}10",
      "settings.tertiary_3edRowBackground": "${colors.transparent}",
      "settings.headerForeground": "${colors.offWhite}",
      "settings.modifiedItemIndicator": "${colors.secondary_2}",
      "settings.numberInputBackground": "${colors.white}05",
      "settings.numberInputBorder": "${colors.white}10",
      "settings.numberInputForeground": "${colors.offWhite}",
      "settings.textInputBackground": "${colors.white}05",
      "settings.textInputBorder": "${colors.white}10",
      "settings.textInputForeground": "${colors.offWhite}",
      "sideBar.dropBackground": "${colors.secondary_4}80",
      "sideBarSectionHeader.foreground": "${colors.gray}",
      "statusBar.debuggingBackground": "${colors.tertiary_3}",
      "statusBar.debuggingForeground": "${colors.white}",
      "statusBar.noFolderForeground": "${colors.gray}",
      "statusBarItem.activeBackground": "${colors.white}2e",
      "statusBarItem.errorBackground": "${colors.hotRed}",
      "statusBarItem.errorForeground": "${colors.white}",
      "statusBarItem.hoverBackground": "${colors.white}1f",
      "statusBarItem.prominentBackground": "${colors.black}80",
      "statusBarItem.prominentForeground": "${colors.gray}",
      "statusBarItem.prominentHoverBackground": "${colors.black}4d",
      "statusBarItem.remoteBackground": "${colors.tertiary_3}",
      "statusBarItem.remoteForeground": "${colors.offWhite}",
      "symbolIcon.arrayForeground": "${colors.gray}",
      "symbolIcon.booleanForeground": "${colors.gray}",
      "symbolIcon.classForeground": "${colors.brightYellow}",
      "symbolIcon.colorForeground": "${colors.gray}",
      "symbolIcon.constantForeground": "${colors.gray}",
      "symbolIcon.constructorForeground": "${colors.pink}",
      "symbolIcon.enumeratorForeground": "${colors.brightYellow}",
      "symbolIcon.enumeratorMemberForeground": "${colors.secondary_2}",
      "symbolIcon.eventForeground": "${colors.brightYellow}",
      "symbolIcon.fieldForeground": "${colors.secondary_2}",
      "symbolIcon.fileForeground": "${colors.gray}",
      "symbolIcon.folderForeground": "${colors.gray}",
      "symbolIcon.functionForeground": "${colors.pink}",
      "symbolIcon.interfaceForeground": "${colors.secondary_2}",
      "symbolIcon.keyForeground": "${colors.gray}",
      "symbolIcon.keywordForeground": "${colors.gray}",
      "symbolIcon.methodForeground": "${colors.pink}",
      "symbolIcon.moduleForeground": "${colors.gray}",
      "symbolIcon.namespaceForeground": "${colors.gray}",
      "symbolIcon.nullForeground": "${colors.gray}",
      "symbolIcon.numberForeground": "${colors.gray}",
      "symbolIcon.objectForeground": "${colors.gray}",
      "symbolIcon.operatorForeground": "${colors.gray}",
      "symbolIcon.packageForeground": "${colors.gray}",
      "symbolIcon.propertyForeground": "${colors.gray}",
      "symbolIcon.referenceForeground": "${colors.gray}",
      "symbolIcon.snippetForeground": "${colors.gray}",
      "symbolIcon.stringForeground": "${colors.gray}",
      "symbolIcon.structForeground": "${colors.gray}",
      "symbolIcon.textForeground": "${colors.gray}",
      "symbolIcon.typeParameterForeground": "${colors.gray}",
      "symbolIcon.unitForeground": "${colors.gray}",
      "symbolIcon.variableForeground": "${colors.secondary_2}",
      "terminal.border": "${colors.transparent}",
      "terminal.foreground": "${colors.gray}",
      "terminal.selectionBackground": "${colors.selection}",
      "terminalCommandDecoration.errorBackground": "${colors.hotRed}",
      "terminalCommandDecoration.successBackground": "${colors.primary_1}",
      "terminalCommandDecoration.defaultBackground": "${colors.tertiary_1}",
      "testing.iconErrored": "${colors.hotRed}",
      "testing.iconFailed": "${colors.hotRed}",
      "testing.iconPassed": "${colors.primary_1}",
      "testing.iconQueued": "${colors.brightYellow}",
      "testing.iconSkipped": "${colors.secondary_4}",
      "testing.iconUnset": "${colors.secondary_4}",
      "testing.message.error.decorationForeground": "${colors.hotRed}",
      "testing.message.error.lineBackground": "${colors.hotRed}33",
      "testing.message.hint.decorationForeground": "${colors.secondary_4}b3",
      "testing.message.info.decorationForeground": "${colors.secondary_2}",
      "testing.message.info.lineBackground": "${colors.secondary_1}33",
      "testing.message.warning.decorationForeground": "${colors.brightYellow}",
      "testing.message.warning.lineBackground": "${colors.brightYellow}33",
      "testing.peekBorder": "${colors.hotRed}",
      "testing.runAction": "${colors.primary_1}",
      "textBlockQuote.background": "${colors.secondary_4}1a",
      "textBlockQuote.border": "${colors.secondary_1}80",
      "textCodeBlock.background": "${colors.black}50",
      "textPreformat.foreground": "${colors.offWhite}",
      "textSeparator.foreground": "${colors.white}2e",
      "tree.tableColumnsBorder": "${colors.gray}20",
      "welcomePage.progress.background": "${colors.white}05",
      "welcomePage.progress.foreground": "${colors.primary_2}",
      "welcomePage.tileBackground": "${colors.bg}",
      "welcomePage.tileHoverBackground": "${colors.tertiary_3}"
    },
    "tokenColors": [
      {
        "scope": ["entity.name.type.class.cs", "variable.other.constant.js"],
        "settings": {
          "foreground": "${colors.primary_1}"
        }
      },
      {
        "scope": ["entity.name.type.cs", "entity.name.type.namespace.cs"],
        "settings": {
          "foreground": "${colors.primary_1}"
        }
      },
      {
        "scope": ["entity.name", "variable.other"],
        "settings": {
          "foreground": "${colors.secondary_2}"
        }
      },
      {
        "scope": ["entity.name.function", "entity.name.function.js", "variable.other.object.property", "variable.other.property"],
        "settings": {
          "foreground": "${colors.secondary_1}"
        }
      },
      {
        "scope": ["keyword.type"],
        "settings": {
          "foreground": "${colors.primary_1}",
          "fontStyle": "bold"
        }
      },
      {
        "scope": ["comment", "punctuation.definition.comment"],
        "settings": {
          "foreground": "${colors.tertiary_3}"
        }
      },
      {
        "scope": ["storage.modifier", "keyword", "keyword.other", "storage.type", "keyword.control"],
        "settings": {
          "foreground": "${colors.tertiary_1}"
        }
      },
      {
        "scope": ["string"],
        "settings": {
          "foreground": "${colors.secondary_3}"
        }
      },
      {
        "scope": ["keyword.control.flow"],
        "settings": {
          "foreground": "${colors.tertiary_1}"
        }
      }
    ]
  }
  `
}

function svg({ colors }) {
  const circle = (color, i) => `
    <circle
      r="4"
      cy="${Math.ceil((i + 1) / 4) * 10}"
      cx="${((i % 4) + 1) * 10}"
      fill="${color}"
    />`
  return `
  <svg width="200" height="250" viewBox="0 0 50 ${
    Math.ceil(Object.keys(colors).length / 4) * 12
  }" xmlns="http://www.w3.org/2000/svg">
    ${Object.values(colors).map(circle).join('')}
  </svg>
  `
}

module.exports.schema = schema
module.exports.base = base
module.exports.noitalics = noitalics
module.exports.storm = storm
module.exports.stormNoitalics = stormNoitalics
module.exports.svg = svg
